version: '3.8'

services:
  # The FastAPI backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gps_backend
    restart: always
    # For development, you can mount the code to see changes without rebuilding
    # volumes:
    #   - ./backend:/app
    ports:
      - "8000:8000"

  # The Streamlit frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gps_frontend
    restart: always
    # volumes:
    #   - ./frontend:/app
    ports:
      - "8501:8501"
    depends_on:
      - backend
